fibe_www_conf:
    resource: "@fibeWWWConfBundle/Controller/"
    prefix:   /

idci_simple_schedule:
    resource: "../../vendor/idci/simple-schedule-bundle/IDCI/Bundle/SimpleScheduleBundle/Controller"
    type:     annotation
    prefix:   /admin
    
idci_exporter:
    resource: "../../vendor/idci/exporter-bundle/IDCI/Bundle/ExporterBundle/Controller"
    type:     annotation

login:
    pattern:   /login
    defaults:  { _controller: fibeSecurityBundle:Security:login }
    
login_check:
    pattern:   /login_check
 
logout:
    pattern:   /logout
