<?php

namespace fibe\Bundle\WWWConfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SWCLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SWCLinkRepository extends EntityRepository
{
}
